[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wn-kindler"
version = "0.0.1"
dependencies = [
    "Click",
]

[project.scripts]
wn-kindler = "wnk:main"