[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wn-kindler"
dependencies = [
    "Click",
    "beautifulSoup4"
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "wnk.VERSION"}

[project.scripts]
wn-kindler = "wnk:commands"